/**
 * Sharktastica matrix_minim.csv uses display tokens (e.g. Grv, FwSlash), not k_*.
 * These map 1:1 to app keyIds; hidden legs mirror qmkKeyIdMap aux keys.
 */
export const MINIM_SHARK_TO_KEYID = {
  Grv: "backtick",
  Esc: "esc",
  Caps: "caps_lock",
  Tab: "tab",
  Lalt: "left_alt",
  Lctrl: "left_ctrl",
  Ralt: "right_alt",
  Rctrl: "right_ctrl",
  Lwin: "os_left",
  Rwin: "os_right",
  Rmenu: "app_menu",
  Space: "space",
  Enter: "enter_main",
  LShift: "left_shift",
  LShiftHid: "matrix_aux_lsh",
  RShift: "right_shift",
  RShiftHid: "matrix_aux_rsh",
  EnterHid: "matrix_aux_enter",
  BackspcHid: "matrix_aux_bsp",
  Backspace: "backspace",
  BackSlash: "backslash",
  PrtScrn: "print_screen",
  ScrLck: "scroll_lock",
  PauseBr: "pause_break",
  Up: "arrow_up",
  Down: "arrow_down",
  Left: "arrow_left",
  Right: "arrow_right",
  Pgup: "page_up",
  PgDn: "page_down",
  FwSlash: "slash",
  Home: "home",
  Ins: "insert",
  Del: "delete",
  End: "end",
  A: "a",
  B: "b",
  C: "c",
  D: "d",
  E: "e",
  F: "f",
  G: "g",
  H: "h",
  I: "i",
  J: "j",
  K: "k",
  L: "l",
  M: "m",
  N: "n",
  O: "o",
  P: "p",
  Q: "q",
  R: "r",
  S: "s",
  T: "t",
  U: "u",
  V: "v",
  W: "w",
  X: "x",
  Y: "y",
  Z: "z",
  "0": "digit_0",
  "1": "digit_1",
  "2": "digit_2",
  "3": "digit_3",
  "4": "digit_4",
  "5": "digit_5",
  "6": "digit_6",
  "7": "digit_7",
  "8": "digit_8",
  "9": "digit_9",
  F1: "f1",
  F2: "f2",
  F3: "f3",
  F4: "f4",
  F5: "f5",
  F6: "f6",
  F7: "f7",
  F8: "f8",
  F9: "f9",
  F10: "f10",
  F11: "f11",
  F12: "f12",
  ",": "comma",
  "-": "minus",
  ".": "period",
  "[": "bracket_left",
  "]": "bracket_right",
  "'": "quote",
  ";": "semicolon",
  "=": "equal",
};

export function keyIdForMinimSharkLabel(label) {
  const s = String(label);
  if (Object.prototype.hasOwnProperty.call(MINIM_SHARK_TO_KEYID, s)) {
    return MINIM_SHARK_TO_KEYID[s];
  }
  throw new Error(`minim: unknown label ${JSON.stringify(s)}`);
}
