/**
 * k_* (QMK-style) from sharktastica CSVs → app keyId.
 * Unknown k_* (e.g. board-specific) → `qmk_*` safe slug.
 */
export const QMK_TO_KEYID = {
  k_lalt: "left_alt",
  k_ralt: "right_alt",
  k_space: "space",
  k_lctrl: "left_ctrl",
  k_rctrl: "right_ctrl",
  k_lshift: "left_shift",
  k_rshift: "right_shift",
  k_caps: "caps_lock",
  k_tab: "tab",
  k_backspace: "backspace",
  k_backsl: "backslash",
  k_tild: "backtick",
  k_esc: "esc",
  k_prscr: "print_screen",
  k_scrl: "scroll_lock",
  k_pause: "pause_break",
  k_q: "q",
  k_w: "w",
  k_e: "e",
  k_r: "r",
  k_t: "t",
  k_y: "y",
  k_u: "u",
  k_i: "i",
  k_o: "o",
  k_p: "p",
  k_lbrc: "bracket_left",
  k_rbrc: "bracket_right",
  k_a: "a",
  k_s: "s",
  k_d: "d",
  k_f: "f",
  k_g: "g",
  k_h: "h",
  k_j: "j",
  k_k: "k",
  k_l: "l",
  k_semicolon: "semicolon",
  k_singlequote: "quote",
  k_z: "z",
  k_x: "x",
  k_c: "c",
  k_v: "v",
  k_b: "b",
  k_n: "n",
  k_m: "m",
  k_cm: "comma",
  k_period: "period",
  k_nuhs: "intl_backslash",
  k_equals: "equal",
  k_minus: "minus",
  k_1: "digit_1",
  k_2: "digit_2",
  k_3: "digit_3",
  k_4: "digit_4",
  k_5: "digit_5",
  k_6: "digit_6",
  k_7: "digit_7",
  k_8: "digit_8",
  k_9: "digit_9",
  k_0: "digit_0",
  k_f1: "f1",
  k_f2: "f2",
  k_f3: "f3",
  k_f4: "f4",
  k_f5: "f5",
  k_f6: "f6",
  k_f7: "f7",
  k_f8: "f8",
  k_f9: "f9",
  k_f10: "f10",
  k_f11: "f11",
  k_f12: "f12",
  k_f13: "f13",
  k_f14: "f14",
  k_f15: "f15",
  k_f16: "f16",
  k_f17: "f17",
  k_f18: "f18",
  k_f19: "f19",
  k_f20: "f20",
  k_f21: "f21",
  k_f22: "f22",
  k_f23: "f23",
  k_f24: "f24",
  k_lb1: "ex1",
  k_lb2: "ex2",
  k_lb3: "ex3",
  k_lb4: "ex4",
  k_lb5: "ex5",
  k_lb6: "ex6",
  k_lb7: "ex7",
  k_lb8: "ex8",
  k_lb9: "ex9",
  k_lb10: "ex10",
  k_left: "arrow_left",
  k_right: "arrow_right",
  k_up: "arrow_up",
  k_down: "arrow_down",
  k_ins: "insert",
  k_del: "delete",
  k_home: "home",
  k_end: "end",
  k_pgup: "page_up",
  k_pgdn: "page_down",
  k_return: "enter_main",
  k_navmid: "nav_center",
  k_fwslash: "slash",
  k_nubs: "euro1",
  k_code: "lang5_code",
  kp_0: "kp_0",
  kp_1: "kp_1",
  kp_2: "kp_2",
  kp_3: "kp_3",
  kp_4: "kp_4",
  kp_5: "kp_5",
  kp_6: "kp_6",
  kp_7: "kp_7",
  kp_8: "kp_8",
  kp_9: "kp_9",
  kp_dot: "kp_decimal",
  kp_nl: "num_lock",
  kp_enter: "kp_enter",
  kp_plus: "kp_plus",
  kp_plus_hidden: "matrix_aux_kp_plus",
  kp_plus_hidden2: "matrix_aux_kp_plus2",
  kp_plus_hidden1: "matrix_aux_kp_plus1",
  kp_0_hidden: "matrix_aux_kp_0",
  k_bsp_hidden: "matrix_aux_bsp",
  k_rshift_hidden: "matrix_aux_rsh",
  k_rwin: "os_right",
  k_lwin: "os_left",
  k_rmenu: "app_menu",
  k_menu: "app_menu",
  kp_div: "kp_slash",
  kp_mult: "kp_asterisk",
  k_enter_hidden: "matrix_aux_enter",
  k_enter: "enter_main",
};

export function keyIdForQmk(q) {
  if (QMK_TO_KEYID[q]) {
    return QMK_TO_KEYID[q];
  }
  const s = String(q);
  if (s.startsWith("k_")) {
    return `qmk_${s.replace(/^k_/, "").replace(/[^a-z0-9_]/gi, "_")}`;
  }
  return `qmk_raw_${s.replace(/[^a-z0-9_]/gi, "_")}`;
}
